# Generated by Django 3.1.2 on 2020-10-31 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Public',
        ),
    ]
